---

- name: To install Default jre and update repo
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - default-jre
    - python-software-properties
    - default-jdk
    
- name: To add oracle java repo
  apt_repository: repo='ppa:webupd8team/java'
  
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 
  
- name: auto accept oracle jdk license
  shell: echo oracle-{{ version }}-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: To install different java versions
  apt: 
    name: "{{ java_versions}}"
    state: present
    force: yes
  
- name: Copy the Environment file
  template:
    src: environment.j2
    dest: /etc/environment

